power:
  b_size: 2500
  nb_steps_dual: 20
  l1: 0.
  nb_epoch: 2500
  nb_flow:
    - 1
    - 5
  weight_decay: 1e-5
  learning_rate: 1e-3
  Normalizers:
    - type:
        Class:
          Name: AffineNormalizer
          args:
      h_dim: 2
    - type:
        Class:
          Name: MonotonicNormalizer
          args:
            nb_steps: 15
            solver: "CC"
            integrand_net:
              Class:
                Name: IntegrandNet
                args:
                  hidden: [100, 100, 100]
                  cond_in: 30
      h_dim: 30
  Conditioners:
      - type:
        Class:
          Name: CouplingConditioner
          args:
            in_size: VAR_dim
            hidden: [60, 60, 60]
            out_size: VAR_h_dim
      - type:
        Class:
          Name: AutoregressiveConditioner
          args:
            args:
              in_size: VAR_dim
              hidden: [60, 60, 60]
              out_size: VAR_h_dim
      - type:
          Class:
            Name: DAGConditioner
            args:
              in_size: VAR_dim
              soft_thresholding: True
              h_thresh: 0.
              hidden: [60, 60, 60]
              out_size: VAR_h_dim
              gumble_T: .5