power-mono-DAG:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [60, 60, 60, 30]
  nb_steps_dual: 30
  l1: 0.
  gumble_T: .5
  normalizer: 'monotonic'
  int_net: [100, 100, 100]
  nb_steps: 20
  solver: 'CC'

power-affine-DAG:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [60, 60, 60, 2]
  nb_steps_dual: 30
  l1: 0.
  gumble_T: .5
  normalizer: 'affine'

power-mono-coupling:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'Coupling'
  emb_net: [60, 60, 60, 30]
  normalizer: 'monotonic'
  int_net: [100, 100, 100]
  nb_steps: 20
  solver: 'CC'

power-affine-coupling:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'Coupling'
  emb_net: [60, 60, 60, 2]
  normalizer: 'affine'

power-mono-autoregressive:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [60, 60, 60, 30]
  normalizer: 'monotonic'
  int_net: [100, 100, 100]
  nb_steps: 20
  solver: 'CC'

power-affine-autoregressive:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [60, 60, 60, 2]
  normalizer: 'affine'